socket_path: "/tmp/yproxy.sock"
interconnect_socket_path: "/tmp/ic.sock"
log_level: debug
debug_port: 2113
debug_minutes: 120

storage:
  storage_prefix: "/tmp/yezzey-fs-storage/"
  storage_bucket: "gpyezzey"
  storage_region: "us-west-2"
  storage_type: "fs"
  tablespace_map:
    "pg_default": "gpyezzey"
    "tab1": "gpyezzey"
    "tab2": "gpyezzey"

backup_storage:
  storage_prefix: "/tmp/yezzey-fs-backup/"
  storage_bucket: "gpyezzey"
  storage_region: "us-west-2"
  storage_type: "fs"

vacuum:
  check_backup: false
  protection_window: 0s
