
CREATE EXTENSION yezzey;

ALTER EXTENSION yezzey UPDATE TO '1.8';

ALTER EXTENSION yezzey UPDATE TO '1.8.1';

ALTER EXTENSION yezzey UPDATE TO '1.8.2';

ALTER EXTENSION yezzey UPDATE TO '1.8.3';

ALTER EXTENSION yezzey UPDATE TO '1.8.4';

ALTER EXTENSION yezzey UPDATE TO '1.8.5';


DROP EXTENSION yezzey;
CHECKPOINT;
