
CREATE EXTENSION yezzey VERSION '1.0';

ALTER EXTENSION yezzey UPDATE TO '1.8';

ALTER EXTENSION yezzey UPDATE TO '1.8.1';

ALTER EXTENSION yezzey UPDATE TO '1.8.2';

ALTER EXTENSION yezzey UPDATE TO '1.8.3';

ALTER EXTENSION yezzey UPDATE TO '1.8.4';

ALTER EXTENSION yezzey UPDATE TO '1.8.5';

ALTER EXTENSION yezzey UPDATE TO '1.8.6';

ALTER EXTENSION yezzey UPDATE TO '1.8.7';

ALTER EXTENSION yezzey UPDATE TO '1.8.8';

DROP EXTENSION yezzey;
CHECKPOINT;
