name: Format

on:
  push:
    branches: [ v1.8_opengpdb, master ]
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/v1.8_opengpdb' }}

jobs:
  format:
    name: check-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make -f Makefile.fmt check-format
